googleAnalytics = "G-TLNN4F1ZM1"

baseURL = 'https://chipacu.github.io/aed-docs/'
languageCode = 'es-ar'
title = 'Notae Chipacus 🤓 AED 23 | K1.6'
theme = 'hugo-book'

[params]

  BookTheme = 'dark'

  bookCollapseSection = true
