baseURL = 'https://chipacu.github.io/aed-docs/'
languageCode = 'es-ar'
title = '♛ Apuntes de chipaco | AED 2023 K1.6'
theme = 'hugo-book'

[params]

  BookTheme = 'light'

  BookMenuBundle = '/menu'

  bookCollapseSection = true